<?php

/**
 * Static UI translations for front-end templates.
 * Usage in Twig: {{ t('key') }}
 */
return [
    'nl' => [
        'home' => 'Home',
        'cart' => 'Winkelwagen',
        'shop' => 'Shop',
        'appointments' => 'Afspraken',
        'checkout' => 'Afrekenen',
        'payment_success' => 'Betaling geslaagd',
        'payment_cancel' => 'Betaling geannuleerd',
        'contact' => 'Contact',
        'about' => 'Over ons',
        'read_more' => 'Lees meer',
        'back' => 'Terug',
        'services' => 'Diensten',
        'navigation' => 'Navigatie',
        'all_rights' => 'Alle rechten voorbehouden.',
        'make_appointment' => 'Maak een afspraak',
        'discover_more' => 'Ontdek meer',
        'published' => 'Gepubliceerd',
        'draft' => 'Concept',
        'no_pages_found' => 'Geen pagina\'s gevonden.',
        'login' => 'Inloggen',
        'register' => 'Registreren',
        'logout' => 'Uitloggen',
        // Shop
        'webshop' => 'Webshop',
        'our_products' => 'Onze producten',
        'categories' => 'Categorieën',
        'all_products' => 'Alle producten',
        'no_products' => 'Geen producten gevonden.',
        'no_products_category' => 'Geen producten in deze categorie.',
        'back_to_shop' => 'Terug naar shop',
        'incl_vat' => 'Incl. BTW',
        'price_on_request' => 'Prijs op aanvraag',
        'on_request' => 'Op aanvraag',
        'in_stock' => 'Op voorraad',
        'out_of_stock' => 'Uitverkocht',
        'add_to_cart' => 'In winkelwagen',
        'request_quote' => 'Vraag offerte aan',
        'description' => 'Beschrijving',
        'continue_shopping' => 'Verder winkelen',
        'per_piece' => 'per stuk',
        'cart_empty' => 'Uw winkelwagen is leeg.',
        'view_shop' => 'Bekijk shop',
        'total' => 'Totaal',
        // Checkout
        'personal_info' => 'Persoonlijke gegevens',
        'first_name' => 'Voornaam',
        'last_name' => 'Achternaam',
        'email_address' => 'E-mailadres',
        'phone' => 'Telefoon',
        'shipping_address' => 'Verzendadres',
        'address' => 'Adres',
        'postal_code' => 'Postcode',
        'city' => 'Stad',
        'payment_method' => 'Betaalmethode',
        'notes_optional' => 'Opmerkingen (optioneel)',
        'overview' => 'Overzicht',
        'place_order' => 'Bestelling plaatsen',
        'secure_payment' => 'Veilig betalen via Mollie',
        'thank_you_order' => 'Bedankt voor uw bestelling!',
        'payment_received' => 'Uw betaling is ontvangen. U ontvangt een bevestiging per e-mail.',
        'payment_cancelled_msg' => 'Uw betaling is geannuleerd. Uw winkelwagen is bewaard.',
        'back_to_cart' => 'Terug naar winkelwagen',
    ],
    'fr' => [
        'home' => 'Accueil',
        'cart' => 'Panier',
        'shop' => 'Boutique',
        'appointments' => 'Rendez-vous',
        'checkout' => 'Paiement',
        'payment_success' => 'Paiement réussi',
        'payment_cancel' => 'Paiement annulé',
        'contact' => 'Contact',
        'about' => 'À propos',
        'read_more' => 'Lire la suite',
        'back' => 'Retour',
        'services' => 'Services',
        'navigation' => 'Navigation',
        'all_rights' => 'Tous droits réservés.',
        'make_appointment' => 'Prendre rendez-vous',
        'discover_more' => 'Découvrir plus',
        'published' => 'Publié',
        'draft' => 'Brouillon',
        'no_pages_found' => 'Aucune page trouvée.',
        'login' => 'Connexion',
        'register' => 'S\'inscrire',
        'logout' => 'Déconnexion',
        // Shop
        'webshop' => 'Boutique en ligne',
        'our_products' => 'Nos produits',
        'categories' => 'Catégories',
        'all_products' => 'Tous les produits',
        'no_products' => 'Aucun produit trouvé.',
        'no_products_category' => 'Aucun produit dans cette catégorie.',
        'back_to_shop' => 'Retour à la boutique',
        'incl_vat' => 'TVA incluse',
        'price_on_request' => 'Prix sur demande',
        'on_request' => 'Sur demande',
        'in_stock' => 'En stock',
        'out_of_stock' => 'Épuisé',
        'add_to_cart' => 'Ajouter au panier',
        'request_quote' => 'Demander un devis',
        'description' => 'Description',
        'continue_shopping' => 'Continuer vos achats',
        'per_piece' => 'par pièce',
        'cart_empty' => 'Votre panier est vide.',
        'view_shop' => 'Voir la boutique',
        'total' => 'Total',
        // Checkout
        'personal_info' => 'Informations personnelles',
        'first_name' => 'Prénom',
        'last_name' => 'Nom de famille',
        'email_address' => 'Adresse e-mail',
        'phone' => 'Téléphone',
        'shipping_address' => 'Adresse de livraison',
        'address' => 'Adresse',
        'postal_code' => 'Code postal',
        'city' => 'Ville',
        'payment_method' => 'Méthode de paiement',
        'notes_optional' => 'Remarques (facultatif)',
        'overview' => 'Aperçu',
        'place_order' => 'Passer la commande',
        'secure_payment' => 'Paiement sécurisé via Mollie',
        'thank_you_order' => 'Merci pour votre commande !',
        'payment_received' => 'Votre paiement a été reçu. Vous recevrez une confirmation par e-mail.',
        'payment_cancelled_msg' => 'Votre paiement a été annulé. Votre panier a été sauvegardé.',
        'back_to_cart' => 'Retour au panier',
    ],
];
